### ISSUE TITLE
Couldn't find any attribute eval methods

### ISSUE THREAD

**Issue by slavakurilyak** [larskotthoff/autoweka#42]
Running:

```
$ java -cp autoweka.jar weka.classifiers.meta.AutoWEKAClassifier -t dataset.arff -timeLimit 15 -no-cv
```

I get the following error:

```
java.lang.RuntimeException: Failed to prepare the experiment
	at autoweka.smac.SMACExperimentConstructor.prepareExperiment(SMACExperimentConstructor.java:46)
	at autoweka.ExperimentConstructor.run(ExperimentConstructor.java:238)
	at autoweka.ExperimentConstructor.buildSingle(ExperimentConstructor.java:158)
	at weka.classifiers.meta.AutoWEKAClassifier.buildClassifier(AutoWEKAClassifier.java:333)
	at weka.classifiers.evaluation.Evaluation.evaluateModel(Evaluation.java:1527)
	at weka.classifiers.Evaluation.evaluateModel(Evaluation.java:650)
	at weka.classifiers.AbstractClassifier.runClassifier(AbstractClassifier.java:141)
	at weka.classifiers.meta.AutoWEKAClassifier.main(AutoWEKAClassifier.java:263)
Caused by: java.lang.RuntimeException: Couldn't find any attribute eval methods
	at autoweka.ExperimentConstructor.generateAlgorithmParameterConditionalGroupForDAG(ExperimentConstructor.java:390)
	at autoweka.smac.SMACExperimentConstructor.printParamFile(SMACExperimentConstructor.java:258)
	at autoweka.smac.SMACExperimentConstructor.prepareExperiment(SMACExperimentConstructor.java:31)
	... 7 more
```

Please advise.

**Comment by larskotthoff** [comment]
What directory are you running this from? Do you have the params folder that is part of the distribution?

**Comment by slavakurilyak** [comment]
I'm running the java command from: `/Users/skurilyak/wekafiles/packages/Auto-WEKA`, which contains the `params` folder

**Comment by larskotthoff** [comment]
Can you post your data please so that I can try to reproduce the problem?

**Comment by slavakurilyak** [comment]
Here's a zip file - [dataset.arff.zip](https://github.com/automl/autoweka/files/956262/dataset.arff.zip)

**Comment by larskotthoff** [comment]
Sorry, I can't reproduce this. Does it work if you run through the GUI?

**Comment by slavakurilyak** [comment]
Yes, the GUI works. The command line on my macOS Sierra doesn't

**Comment by larskotthoff** [comment]
Works fine for me on El Capitan. Sorry, I don't have access to a Sierra machine to test there.

**Comment by slavakurilyak** [comment]
Thanks @larskotthoff
