### ISSUE TITLE
Base learner must implement Randomizable

### ISSUE THREAD

**Issue by slavakurilyak** [larskotthoff/autoweka#44]
Running:

```
$ java -cp autoweka.jar weka.classifiers.meta.AutoWEKAClassifier -t iris.arff
```

I get the following warning:
```
2017-05-02 11:04:39.484 [Thread-1] WARN AutoWEKAClassifier - 2017-05-02 11:04:39.484 [main] WARN Experiment - [WARN ] [PROCESS-ERR]  2017-05-02 11:04:39.467 [Thread-0] WARN ClassifierRunner - Training classifier (weka.classifiers.meta.RandomCommittee [-I, 5, -S, 1, -W, weka.classifiers.rules.OneR, --, -B, 3]) failed: Base learner must implement Randomizable!
2017-05-02 11:04:39.485 [Thread-1] WARN AutoWEKAClassifier - 2017-05-02 11:04:39.484 [main] WARN Experiment - [WARN ] [PROCESS-ERR]  java.lang.IllegalArgumentException: Base learner must implement Randomizable!
2017-05-02 11:04:39.485 [Thread-1] WARN AutoWEKAClassifier - 2017-05-02 11:04:39.484 [main] WARN Experiment - [WARN ] [PROCESS-ERR]  	at weka.classifiers.meta.RandomCommittee.buildClassifier(RandomCommittee.java:150)
2017-05-02 11:04:39.485 [Thread-1] WARN AutoWEKAClassifier - 2017-05-02 11:04:39.485 [main] WARN Experiment - [WARN ] [PROCESS-ERR]  	at autoweka.ClassifierRunner$BuilderThread.doWork(ClassifierRunner.java:459)
2017-05-02 11:04:39.485 [Thread-1] WARN AutoWEKAClassifier - 2017-05-02 11:04:39.485 [main] WARN Experiment - [WARN ] [PROCESS-ERR]  	at autoweka.WorkerThread.run(WorkerThread.java:26)

2017-05-02 11:05:59.883 [Thread-1] WARN AutoWEKAClassifier - 2017-05-02 11:05:59.883 [main] WARN Experiment - [WARN ] [PROCESS-ERR]  2017-05-02 11:05:59.836 [Thread-0] WARN ClassifierRunner - Training classifier (weka.classifiers.meta.RandomCommittee [-I, 34, -S, 1, -W, weka.classifiers.lazy.IBk, --, -K, 5, -I]) failed: Base learner must implement Randomizable!
2017-05-02 11:05:59.883 [Thread-1] WARN AutoWEKAClassifier - 2017-05-02 11:05:59.883 [main] WARN Experiment - [WARN ] [PROCESS-ERR]  java.lang.IllegalArgumentException: Base learner must implement Randomizable!
2017-05-02 11:05:59.883 [Thread-1] WARN AutoWEKAClassifier - 2017-05-02 11:05:59.883 [main] WARN Experiment - [WARN ] [PROCESS-ERR]  	at weka.classifiers.meta.RandomCommittee.buildClassifier(RandomCommittee.java:150)
2017-05-02 11:05:59.883 [Thread-1] WARN AutoWEKAClassifier - 2017-05-02 11:05:59.883 [main] WARN Experiment - [WARN ] [PROCESS-ERR]  	at autoweka.ClassifierRunner$BuilderThread.doWork(ClassifierRunner.java:459)
2017-05-02 11:05:59.883 [Thread-1] WARN AutoWEKAClassifier - 2017-05-02 11:05:59.883 [main] WARN Experiment - [WARN ] [PROCESS-ERR]  	at autoweka.WorkerThread.run(WorkerThread.java:26)

...
```

I'm using macOS Sierra, version 10.12.4 (16E195)

**Comment by slavakurilyak** [comment]
Here's the dataset - [iris.arff.zip](https://github.com/automl/autoweka/files/972033/iris.arff.zip)

**Comment by larskotthoff** [comment]
That warning is harmless. Auto-WEKA doesn't encode these requirements and you may occasionally see such warnings.
