### ISSUE TITLE
 java.lang.NoClassDefFoundError: javax/xml/bind/JAXBContext

### ISSUE THREAD

**Issue by dfalessi** [larskotthoff/autoweka#61]
Hi there,
  I am using Windows 10,Weka 3.8.2, Autoweka-2.6.zip. Java version is:
***********
java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
***************

Here is the log of the error I got: 

*************
09:53:15: Weka Explorer
09:53:15: (c) 1999-2017 The University of Waikato, Hamilton, New Zealand
09:53:15: web: http://www.cs.waikato.ac.nz/~ml/weka/
09:53:15: Started on Saturday, 21 April 2018
09:53:26: Base relation is now xalan2-weka.filters.unsupervised.attribute.Remove-R1-2 (3320 instances)
09:53:26: java.lang.NullPointerException
09:53:30: Started Auto-WEKA for xalan2-weka.filters.unsupervised.attribute.Remove-R1-2
********************

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by weka.core.WekaPackageClassLoaderManager (file:/C:/Program%20Files/Weka-3-8/weka.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of weka.core.WekaPackageClassLoaderManager
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
java.lang.NullPointerException
        weka.core.Instances.<init>(Instances.java:179)
        weka.gui.explorer.ClassifierPanel.updateCapabilitiesFilter(ClassifierPanel.java:3262)
        weka.gui.explorer.ClassifierPanel.capabilitiesFilterChanged(ClassifierPanel.java:3302)
        weka.gui.explorer.Explorer.notifyCapabilitiesFilterListener(Explorer.java:343)
        weka.gui.explorer.PreprocessPanel$21.run(PreprocessPanel.java:775)
        java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
        java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        java.desktop/java.awt.EventQueue.access$500(Unknown Source)
        java.desktop/java.awt.EventQueue$3.run(Unknown Source)
        java.desktop/java.awt.EventQueue$3.run(Unknown Source)
        java.base/java.security.AccessController.doPrivileged(Native Method)
        java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
        java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

        at weka.core.Instances.<init>(Instances.java:179)
        at weka.gui.explorer.ClassifierPanel.updateCapabilitiesFilter(ClassifierPanel.java:3262)
        at weka.gui.explorer.ClassifierPanel.capabilitiesFilterChanged(ClassifierPanel.java:3302)
        at weka.gui.explorer.Explorer.notifyCapabilitiesFilterListener(Explorer.java:343)
        at weka.gui.explorer.PreprocessPanel$21.run(PreprocessPanel.java:775)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.EventQueue.access$500(Unknown Source)
        at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
        at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "Thread-5" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBContext
        autoweka.XmlSerializable.toXML(XmlSerializable.java:59)
        autoweka.XmlSerializable.toXML(XmlSerializable.java:43)
        autoweka.ExperimentConstructor.run(ExperimentConstructor.java:245)
        autoweka.ExperimentConstructor.buildSingle(ExperimentConstructor.java:158)
        weka.classifiers.meta.AutoWEKAClassifier.buildClassifier(AutoWEKAClassifier.java:336)
        weka.gui.explorer.AutoWEKAPanel$13.run(AutoWEKAPanel.java:451)

        at autoweka.XmlSerializable.toXML(XmlSerializable.java:59)
        at autoweka.XmlSerializable.toXML(XmlSerializable.java:43)
        at autoweka.ExperimentConstructor.run(ExperimentConstructor.java:245)
        at autoweka.ExperimentConstructor.buildSingle(ExperimentConstructor.java:158)
        at weka.classifiers.meta.AutoWEKAClassifier.buildClassifier(AutoWEKAClassifier.java:336)
        at weka.gui.explorer.AutoWEKAPanel$13.run(AutoWEKAPanel.java:451)
Caused by: java.lang.ClassNotFoundException: [weka.core.WekaPackageLibIsolatingClassLoader (Auto-WEKA)] Unable to find class: javax.xml.bind.JAXBContext
        at weka.core.WekaPackageLibIsolatingClassLoader.findClass(WekaPackageLibIsolatingClassLoader.java:509)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 6 more

**Comment by larskotthoff** [comment]
I assume that this happens when you try to save a model? Do you get this only in Auto-WEKA or also for other models?

**Comment by uazadi** [comment]
I am having the same problem.
Specifically, this problem arises both if I click the "start" button both in the Auto-WEKA tab and in the Classify tab. I have no problem to save models in weka, I get this only in Auto-WEKA (as far as I know).
____
**Info on the environment**
- OS: Ubuntu 18.04
- Java: 
	openjdk version "10.0.2" 2018-07-17
	OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4) 
	OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)
- Autoweka (v2.6.1) installed through the Packet Menager of WEKA(v3.8.3)
___
**Printed message** (and log file content)

	Exception in thread "Thread-50" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBContext
	  autoweka.XmlSerializable.toXML(XmlSerializable.java:59)
	  autoweka.XmlSerializable.toXML(XmlSerializable.java:43)
	  autoweka.ExperimentConstructor.run(ExperimentConstructor.java:245)
	  autoweka.ExperimentConstructor.buildSingle(ExperimentConstructor.java:158)
	  weka.classifiers.meta.AutoWEKAClassifier.buildClassifier(AutoWEKAClassifier.java:336)
	  weka.gui.explorer.ClassifierPanel$18.run(ClassifierPanel.java:1456)
	
	  at autoweka.XmlSerializable.toXML(XmlSerializable.java:59)
	  at autoweka.XmlSerializable.toXML(XmlSerializable.java:43)
	  at autoweka.ExperimentConstructor.run(ExperimentConstructor.java:245)
	  at autoweka.ExperimentConstructor.buildSingle(ExperimentConstructor.java:158)
	  at weka.classifiers.meta.AutoWEKAClassifier.buildClassifier(AutoWEKAClassifier.java:336)
	  at weka.gui.explorer.ClassifierPanel$18.run(ClassifierPanel.java:1456)

**Comment by fbarriga** [comment]
It seems to be caused by the version of java virtual machine. Work-around for macOS: https://qili.site/en/auto-weka-issue/
