### ISSUE TITLE
Problem running Auto-WEKA

### ISSUE THREAD

**Issue by vishnukarna438** [larskotthoff/autoweka#95]
Hi,
While running Auto WEKA I am getting this error message. 

Java executable could not be found. Please refer to "known issues " in the Auto-WEKA manual. 

Please help me to resolve this. FYI I am using WEKA version 3.9.5 in macOS Big Sur (11.5.1).

Thank you.

**Comment by larskotthoff** [comment]
Do you have java installed? What version, and how did you install it?

**Comment by vishnukarna438** [comment]
I have downloaded and installed the following version of Java
jre-8u301-macosx-x64
from 
https://java.com/en/download/

**Comment by larskotthoff** [comment]
If you type "java -version" in a terminal, what happens?

**Comment by vishnukarna438** [comment]
It showing like this.

java version "1.8.0_301"
Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.301-b09, mixed mode)

**Comment by simonprovost** [comment]
Hiya guys,

From the known issues section in the Manual I was able to run Auto-WEKA via the GUI of WEKA but an error occurred and I believe we've the same with @vishnukarna438. 

After having chosen the AutoWEKAClassifier, and selected "Use training set" test option and press start from the "classify" tab. I got the following error: "Problem evaluating classifier: Cannot invoke "Java.lang.CharSequence.toString()" because "s" is null".

With the following log:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by weka.core.WekaPackageClassLoaderManager (file:/Applications/weka-3-8-5-azul-zulu.app/Contents/Java/weka.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of weka.core.WekaPackageClassLoaderManager
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Tester set to: weka.experiment.PairedCorrectedTTester
java.lang.NullPointerException: Cannot invoke "weka.core.Instances.numInstances()" because "dataset" is null
	weka.core.Instances.<init>(Instances.java:179)
	weka.gui.explorer.ClassifierPanel.updateCapabilitiesFilter(ClassifierPanel.java:3471)
	weka.gui.explorer.ClassifierPanel.capabilitiesFilterChanged(ClassifierPanel.java:3511)
	weka.gui.explorer.Explorer.notifyCapabilitiesFilterListener(Explorer.java:351)
	weka.gui.explorer.PreprocessPanel$21.run(PreprocessPanel.java:776)
	weka.gui.explorer.PreprocessPanel.setInstances(PreprocessPanel.java:805)
	weka.gui.explorer.PreprocessPanel$24$1.actionPerformed(PreprocessPanel.java:1160)
	java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	java.desktop/java.awt.Component.processMouseEvent(Component.java:6614)
	java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	java.desktop/java.awt.Component.processEvent(Component.java:6379)
	java.desktop/java.awt.Container.processEvent(Container.java:2263)
	java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4990)
	java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
	java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
	java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4548)
	java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489)
	java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2769)
	java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
	java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

	at weka.core.Instances.<init>(Instances.java:179)
	at weka.gui.explorer.ClassifierPanel.updateCapabilitiesFilter(ClassifierPanel.java:3471)
	at weka.gui.explorer.ClassifierPanel.capabilitiesFilterChanged(ClassifierPanel.java:3511)
	at weka.gui.explorer.Explorer.notifyCapabilitiesFilterListener(Explorer.java:351)
	at weka.gui.explorer.PreprocessPanel$21.run(PreprocessPanel.java:776)
	at weka.gui.explorer.PreprocessPanel.setInstances(PreprocessPanel.java:805)
	at weka.gui.explorer.PreprocessPanel$24$1.actionPerformed(PreprocessPanel.java:1160)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6614)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6379)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4990)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4548)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2769)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
[Thread-6] WARN weka.classifiers.meta.AutoWEKAClassifier - WARNING: An illegal reflective access operation has occurred
[Thread-6] WARN weka.classifiers.meta.AutoWEKAClassifier - WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector (file:/Applications/weka-3-8-5-azul-zulu.app/Contents/Java/weka.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
[Thread-6] WARN weka.classifiers.meta.AutoWEKAClassifier - WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector
[Thread-6] WARN weka.classifiers.meta.AutoWEKAClassifier - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[Thread-6] WARN weka.classifiers.meta.AutoWEKAClassifier - WARNING: All illegal access operations will be denied in a future release
[Thread-6] WARN weka.classifiers.meta.AutoWEKAClassifier - 2021-08-11 15:53:52.690 [main] WARN Experiment - WARNING: An illegal reflective access operation has occurred
[Thread-6] WARN weka.classifiers.meta.AutoWEKAClassifier - 2021-08-11 15:53:52.693 [main] WARN Experiment - WARNING: Illegal reflective access by ca.ubc.cs.beta.aeatk.targetalgorithmevaluator.base.cli.CommandLineAlgorithmRun (file:/Users/simonprovost/wekafiles/packages/Auto-WEKA/smac-v2.10.03-master-778/lib/aeatk.jar) to field java.lang.ProcessImpl.pid
[Thread-6] WARN weka.classifiers.meta.AutoWEKAClassifier - 2021-08-11 15:53:52.695 [main] WARN Experiment - WARNING: Please consider reporting this to the maintainers of ca.ubc.cs.beta.aeatk.targetalgorithmevaluator.base.cli.CommandLineAlgorithmRun
[Thread-6] WARN weka.classifiers.meta.AutoWEKAClassifier - 2021-08-11 15:53:52.698 [main] WARN Experiment - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[Thread-6] WARN weka.classifiers.meta.AutoWEKAClassifier - 2021-08-11 15:53:52.699 [main] WARN Experiment - WARNING: All illegal access operations will be denied in a future release
[Thread-6] WARN weka.classifiers.meta.AutoWEKAClassifier - 2021-08-11 15:53:53.179 [main] WARN Experiment - [WARN ] [PROCESS-ERR]  Exception in thread "main" java.lang.NoClassDefFoundError: weka/core/Instance
[Thread-6] WARN weka.classifiers.meta.AutoWEKAClassifier - 2021-08-11 15:53:53.181 [main] WARN Experiment - [WARN ] [PROCESS-ERR]  	at autoweka.Wrapper.run(Wrapper.java:123)
[Thread-6] WARN weka.classifiers.meta.AutoWEKAClassifier - 2021-08-11 15:53:53.183 [main] WARN Experiment - [WARN ] [PROCESS-ERR]  Caused by: java.lang.ClassNotFoundException: weka.core.Instance
[Thread-6] WARN weka.classifiers.meta.AutoWEKAClassifier - 2021-08-11 15:53:53.185 [main] WARN Experiment - [WARN ] [PROCESS-ERR]  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
[Thread-6] WARN weka.classifiers.meta.AutoWEKAClassifier - 2021-08-11 15:53:53.187 [main] WARN Experiment - [WARN ] [PROCESS-ERR]  	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
[Thread-6] WARN weka.classifiers.meta.AutoWEKAClassifier - 2021-08-11 15:53:53.189 [main] WARN Experiment - [WARN ] [PROCESS-ERR]  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[Thread-6] WARN weka.classifiers.meta.AutoWEKAClassifier - 2021-08-11 15:53:53.191 [main] WARN Experiment - [WARN ] [PROCESS-ERR]  	... 2 more
[Thread-6] ERROR weka.classifiers.meta.AutoWEKAClassifier - 2021-08-11 15:53:53.357 [main] ERROR Experiment - [ERROR] Message:  Wrapper did not output anything that matched the expected output ("Result of algorithm run:..."). Please try executing the wrapper directly
[Thread-6] ERROR weka.classifiers.meta.AutoWEKAClassifier - 2021-08-11 15:53:53.367 [main] ERROR Experiment - [ERROR] We tried to call the target algorithm wrapper, but this call failed.
[Thread-6] ERROR weka.classifiers.meta.AutoWEKAClassifier - 2021-08-11 15:53:53.368 [main] ERROR Experiment - [ERROR] The problem is (most likely) somewhere in the wrapper or with the arguments to SMAC.
[Thread-6] ERROR weka.classifiers.meta.AutoWEKAClassifier - 2021-08-11 15:53:53.370 [main] ERROR Experiment - [ERROR] The easiest way to debug this problem is to manually execute the call we tried and see why it did not return the correct result
[Thread-6] WARN weka.classifiers.meta.AutoWEKAClassifier - 2021-08-11 15:53:53.718 [main] WARN SMACTrajectoryParser - Could not find runs_and_results file
[Thread-6] WARN weka.classifiers.meta.AutoWEKAClassifier - 2021-08-11 15:53:53.952 [main] WARN SMACTrajectoryParser - Could not find runs_and_results file
[Thread-6] INFO weka.classifiers.meta.AutoWEKAClassifier - Exception in thread "main" java.lang.RuntimeException: Failed to invoke child process
[Thread-6] INFO weka.classifiers.meta.AutoWEKAClassifier - 	at autoweka.SubProcessWrapper.getErrorAndTime(SubProcessWrapper.java:234)
[Thread-6] INFO weka.classifiers.meta.AutoWEKAClassifier - 	at autoweka.SubProcessWrapper.getErrorAndTime(SubProcessWrapper.java:147)
[Thread-6] INFO weka.classifiers.meta.AutoWEKAClassifier - 	at autoweka.TrajectoryPointPredictionRunner.main(TrajectoryPointPredictionRunner.java:80)
[Thread-6] INFO weka.classifiers.meta.AutoWEKAClassifier - 	at autoweka.tools.ExperimentRunner.main(ExperimentRunner.java:59)
[Thread-6] INFO weka.classifiers.meta.AutoWEKAClassifier - Caused by: java.lang.RuntimeException: Failed to find output line from subprocess wrapper
[Thread-6] INFO weka.classifiers.meta.AutoWEKAClassifier - 	at autoweka.SubProcessWrapper.getErrorAndTime(SubProcessWrapper.java:226)
[Thread-6] INFO weka.classifiers.meta.AutoWEKAClassifier - 	... 3 more
[Thread-5] INFO autoweka.TrajectoryMerger - Experiment /var/folders/xd/hlwb4c2s2qd9rn1b3bgs_1g80000gn/T/autoweka17051283159072276785/Auto-WEKA
[Thread-5] INFO weka.classifiers.meta.AutoWEKAClassifier - Thread 0, best configuration estimate -1.0
[Thread-5] INFO weka.classifiers.meta.AutoWEKAClassifier - classifier: null, arguments: [], attribute search: null, attribute search arguments: [], attribute evaluation: null, attribute evaluation arguments: []
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "s" is null
	java.base/java.lang.String.contains(String.java:2052)
	weka.core.ClassCache.find(ClassCache.java:425)
	weka.core.ClassDiscovery.find(ClassDiscovery.java:212)
	weka.Run.findSchemeMatch(Run.java:82)
	weka.core.ResourceUtils.forName(ResourceUtils.java:76)
	weka.core.Utils.forName(Utils.java:1112)
	weka.classifiers.AbstractClassifier.forName(AbstractClassifier.java:91)
	weka.classifiers.meta.AutoWEKAClassifier.buildClassifier(AutoWEKAClassifier.java:519)
	weka.gui.explorer.ClassifierPanel$20.run(ClassifierPanel.java:1523)

	at java.base/java.lang.String.contains(String.java:2052)
	at weka.core.ClassCache.find(ClassCache.java:425)
	at weka.core.ClassDiscovery.find(ClassDiscovery.java:212)
	at weka.Run.findSchemeMatch(Run.java:82)
	at weka.core.ResourceUtils.forName(ResourceUtils.java:76)
	at weka.core.Utils.forName(Utils.java:1112)
	at weka.classifiers.AbstractClassifier.forName(AbstractClassifier.java:91)
	at weka.classifiers.meta.AutoWEKAClassifier.buildClassifier(AutoWEKAClassifier.java:519)
	at weka.gui.explorer.ClassifierPanel$20.run(ClassifierPanel.java:1523)
```

Java --version output:

> openjdk 15.0.1 2020-10-20
> OpenJDK Runtime Environment (build 15.0.1+9-18)
> OpenJDK 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)

Is anyone have an idea?

**Comment by larskotthoff** [comment]
Please don't post separate issues to the same thread.

@vishnukarna438 Are you running WEKA from the command line as the manual advises?

@simonprovost Have you tried with the latest release from Github?

**Comment by simonprovost** [comment]
My bad I thought it was kinda the same as mine is not easy to find throughout all the issues/closed issues available should I go over another issue for you @larskotthoff ?

I guess so, I mean I downloaded yesterday night WEKA from their official website and got auto-weka from the package manager, isn't the latest version?

**Comment by vishnukarna438** [comment]
No. I am using application only. I don't know how to run WEKA from the command line.
Please advice.
Thank you.

**Comment by larskotthoff** [comment]
You need to open a terminal to type commands in. See the Auto-WEKA manual.

**Comment by vishnukarna438** [comment]
When I run through the terminal, getting this error message.

karnavishnuvardhanareddy@KARNAs-MacBook-Pro ~ % cd /Applications/weka-3-9-5-oracle-jvm.app/Contents/Java/
java -jar weka.jar

cd: no such file or directory: /Applications/weka-3-9-5-oracle-jvm.app/Contents/Java/
Error: Unable to access jarfile weka.jar

When I open the weka-3-9-5 folder from applications there is no weka-3-9-5-oracle-jvm.app. see the screenshot of the folder attached. 
May be because of the wrong java path right. Do I need to install java in weka-3-9-5 folder!!!

<img width="758" alt="Screenshot 2021-08-12 at 14 33 53" src="https://user-images.githubusercontent.com/66513681/129149128-e4505b80-a46e-4aa8-90fd-1738a358d821.png">

**Comment by vishnukarna438** [comment]
I tried to change the path but still not getting.

karnavishnuvardhanareddy@KARNAs-MacBook-Pro ~ % cd /Applications/weka-3-9-5/weka.jar
cd: not a directory: /Applications/weka-3-9-5/weka.jar
karnavishnuvardhanareddy@KARNAs-MacBook-Pro ~ % cd /Applications/weka-3-9-5    
karnavishnuvardhanareddy@KARNAs-MacBook-Pro weka-3-9-5 % cd weka.jar
cd: not a directory: weka.jar
karnavishnuvardhanareddy@KARNAs-MacBook-Pro weka-3-9-5 %

**Comment by vishnukarna438** [comment]
Finally got by giving right path
karnavishnuvardhanareddy@KARNAs-MacBook-Pro weka-3-9-5 % java -jar weka.jar

it opened the application. but while running showing the error

<img width="1018" alt="Screenshot 2021-08-12 at 14 50 26" src="https://user-images.githubusercontent.com/66513681/129151124-c8289216-553e-4448-9fe8-9b09cbaf49ce.png">

**Comment by larskotthoff** [comment]
Hmm, when people had this problem in the past, it was usually a problem with the JDK. You could try installing a different version of the JDK.

**Comment by vishnukarna438** [comment]
OK, I will try and let you know.
Thank you.

**Comment by simonprovost** [comment]
@larskotthoff @vishnukarna438 I do, however, have the same issue. I have verified that with JDK version 16, nothing works, that with JDK version 15, the software runs but the error occurs, and that with JDK version 11, the same error occurs: "Problem evaluating classifier: null". 

I am running weka via the command line with `java -jar weka.jar`; another option would be to do everything via the command line (including running auto-weka), but following the manual instructions, I am unable to locate auto-weka.jar after installing auto-weka via the package manager. 

Any Suggestions/Ideas? Any JDK version to suggest?

Log:

```
[Thread-12] WARN weka.classifiers.meta.AutoWEKAClassifier - WARNING: An illegal reflective access operation has occurred
[Thread-12] WARN weka.classifiers.meta.AutoWEKAClassifier - WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector (file:/Applications/weka-3-8-5-azul-zulu.app/Contents/Java/weka.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
[Thread-12] WARN weka.classifiers.meta.AutoWEKAClassifier - WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector
[Thread-12] WARN weka.classifiers.meta.AutoWEKAClassifier - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[Thread-12] WARN weka.classifiers.meta.AutoWEKAClassifier - WARNING: All illegal access operations will be denied in a future release
[Thread-12] WARN weka.classifiers.meta.AutoWEKAClassifier - 2021-08-13 00:09:45.935 [main] WARN Experiment - WARNING: An illegal reflective access operation has occurred
[Thread-12] WARN weka.classifiers.meta.AutoWEKAClassifier - 2021-08-13 00:09:45.936 [main] WARN Experiment - WARNING: Illegal reflective access by ca.ubc.cs.beta.aeatk.targetalgorithmevaluator.base.cli.CommandLineAlgorithmRun (file:/Users/simonprovost/wekafiles/packages/Auto-WEKA/smac-v2.10.03-master-778/lib/aeatk.jar) to field java.lang.ProcessImpl.pid
[Thread-12] WARN weka.classifiers.meta.AutoWEKAClassifier - 2021-08-13 00:09:45.936 [main] WARN Experiment - WARNING: Please consider reporting this to the maintainers of ca.ubc.cs.beta.aeatk.targetalgorithmevaluator.base.cli.CommandLineAlgorithmRun
[Thread-12] WARN weka.classifiers.meta.AutoWEKAClassifier - 2021-08-13 00:09:45.937 [main] WARN Experiment - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[Thread-12] WARN weka.classifiers.meta.AutoWEKAClassifier - 2021-08-13 00:09:45.937 [main] WARN Experiment - WARNING: All illegal access operations will be denied in a future release
[Thread-12] WARN weka.classifiers.meta.AutoWEKAClassifier - 2021-08-13 00:09:46.153 [main] WARN Experiment - [WARN ] [PROCESS-ERR] Exception in thread "main" java.lang.NoClassDefFoundError: weka/core/Instance
[Thread-12] ERROR weka.classifiers.meta.AutoWEKAClassifier - 2021-08-13 00:09:46.189 [main] ERROR Experiment - [ERROR] Message:  Wrapper did not output anything that matched the expected output ("Result of algorithm run:..."). Please try executing the wrapper directly
[Thread-12] ERROR weka.classifiers.meta.AutoWEKAClassifier - 2021-08-13 00:09:46.194 [main] ERROR Experiment - [ERROR] We tried to call the target algorithm wrapper, but this call failed.
[Thread-12] ERROR weka.classifiers.meta.AutoWEKAClassifier - 2021-08-13 00:09:46.195 [main] ERROR Experiment - [ERROR] The problem is (most likely) somewhere in the wrapper or with the arguments to SMAC.
[Thread-12] ERROR weka.classifiers.meta.AutoWEKAClassifier - 2021-08-13 00:09:46.195 [main] ERROR Experiment - [ERROR] The easiest way to debug this problem is to manually execute the call we tried and see why it did not return the correct result
[Thread-12] WARN weka.classifiers.meta.AutoWEKAClassifier - 2021-08-13 00:09:46.280 [main] WARN SMACTrajectoryParser - Could not find runs_and_results file
[Thread-12] WARN weka.classifiers.meta.AutoWEKAClassifier - 2021-08-13 00:09:46.346 [main] WARN SMACTrajectoryParser - Could not find runs_and_results file
[Thread-12] INFO weka.classifiers.meta.AutoWEKAClassifier - Exception in thread "main" java.lang.RuntimeException: Failed to invoke child process
[Thread-12] INFO weka.classifiers.meta.AutoWEKAClassifier - 	at autoweka.SubProcessWrapper.getErrorAndTime(SubProcessWrapper.java:234)
[Thread-12] INFO weka.classifiers.meta.AutoWEKAClassifier - 	at autoweka.SubProcessWrapper.getErrorAndTime(SubProcessWrapper.java:147)
[Thread-12] INFO weka.classifiers.meta.AutoWEKAClassifier - 	at autoweka.TrajectoryPointPredictionRunner.main(TrajectoryPointPredictionRunner.java:80)
[Thread-12] INFO weka.classifiers.meta.AutoWEKAClassifier - 	at autoweka.tools.ExperimentRunner.main(ExperimentRunner.java:59)
[Thread-12] INFO weka.classifiers.meta.AutoWEKAClassifier - Caused by: java.lang.RuntimeException: Failed to find output line from subprocess wrapper
[Thread-12] INFO weka.classifiers.meta.AutoWEKAClassifier - 	at autoweka.SubProcessWrapper.getErrorAndTime(SubProcessWrapper.java:226)
[Thread-12] INFO weka.classifiers.meta.AutoWEKAClassifier - 	... 3 more
[Thread-11] INFO autoweka.TrajectoryMerger - Experiment /var/folders/xd/hlwb4c2s2qd9rn1b3bgs_1g80000gn/T/autoweka9891351434382893496/Auto-WEKA
[Thread-11] INFO weka.classifiers.meta.AutoWEKAClassifier - Thread 0, best configuration estimate -1.0
[Thread-11] INFO weka.classifiers.meta.AutoWEKAClassifier - classifier: null, arguments: [], attribute search: null, attribute search arguments: [], attribute evaluation: null, attribute evaluation arguments: []
java.lang.NullPointerException
```

**Comment by larskotthoff** [comment]
Hmm, could be that the latest version of Mac OS is limiting the ability of processes to call other processes, i.e. `java` in this case.  I can't test this myself unfortunately. If you have access to a computer running Linux or Windows, I would try that.

**Comment by simonprovost** [comment]
@larskotthoff Thanks for that, Will give it a shot with my google compute engine virtual machine runs (i.e.: Ubuntu v18 LTS) my ML stuff. However, could you provides us with the command line to run Auto-WEKA in CLI? Because I am unable to do the same as in the manual, can you ?

@vishnukarna438 if you are able to find anything let us know.

**Comment by larskotthoff** [comment]
The exact commandline depends on your WEKA installation and operating system. Unfortunately I don't have access to a Mac.

**Comment by simonprovost** [comment]
Lars, the following command line worked on my Ubuntu Linux virtual machine instance: 

```
java -cp ../dest_to_auto_weka_version/autoweka.jar:/dest_to_weka_version/weka.jar weka.classifiers.meta.AutoWEKAClassifier  -t ./iris.arff -timeLimit 1 -no-cv                                                                                               
```

The problem is not yet solved on OSX but a rapid change to Ubuntu solved my issue of using Auto-WEKA. Thank you very much . @vishnukarna438 This comment can probably motivate you to switch onto a Google Compute Engine free instance with Ubuntu LTS 16/18 and go ahead make your experiments!

See you later guys, cheers.

**Comment by larskotthoff** [comment]
Thanks for the feedback!
